name: CI

on:
  push:

env:
  CARGO_TERM_COLOR: always
  BUILD_CONTAINER_NAME: integritee_worker_enclave_test

jobs:
  ##########################################################################
  ##########################################################################
  cargo_test:
    runs-on: ubuntu-latest

    steps:
      # Sporadic error: "  cargo:warning=rocksdb/db/db_impl/db_impl_secondary.cc:684:1: fatal error: error writing to /tmp/ccnRl4w5.s: No space left on device"
      # Sometimes work depending on version, OS, etc.
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
      # TODO or easier: "large-packages: false" above?
      - name: re-add needed packages
        run: |
          sudo apt-get install -y libclang-dev

      - uses: Interstellar-Network/gh-actions/prepare@v3-dev
        with:
          ssh_key_input: ${{ secrets.SSH_KEY_MACHINE_USER_INTERSTELLAR_CI }}
          install_cmake_and_ninja: false
          install_ccache: true
          install_conan: false

      - uses: Interstellar-Network/gh-actions/prepare_rust@v3-dev
        with:
          use_toolchain_toml: "true"
          toolchain_components: ""

      ##########################################################################

      - uses: Interstellar-Network/gh-actions/install-sgx-sdk@v3-dev

      # NOTE: we CAN NOT run "cargo test --release" without "make"
      # ELSE: "error: could not find native static library `Enclave_u`, perhaps an -L flag is missing?"
      - name: Make
        run: |
          make

      # TODO move into separate action? ideally into a JS action "post" that setup ccache?
      # NOTE: remove if using "rust-build-and-test"
      - name: Print ccache/sccache stats
        # display stats even if tests failed
        if: success() || failure()
        run: |
          ccache --show-stats || echo "ccache not found!"
          sccache --show-stats || echo "ccache sccache found!"
        shell: bash

      - name: integritee-service test --all
        run: |
          cd bin/ && touch spid.txt key.txt && ./integritee-service test --all

      - name: cargo test --release
        run: |
          cargo test --release

      # TODO move into separate action? ideally into a JS action "post" that setup ccache?
      # NOTE: remove if using "rust-build-and-test"
      - name: Print ccache/sccache stats
        # display stats even if tests failed
        if: success() || failure()
        run: |
          ccache --show-stats || echo "ccache not found!"
          sccache --show-stats || echo "ccache sccache found!"
        shell: bash

  ##########################################################################
  ##########################################################################
  cargo_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: Interstellar-Network/gh-actions/prepare@v3-dev
        with:
          ssh_key_input: ${{ secrets.SSH_KEY_MACHINE_USER_INTERSTELLAR_CI }}
          install_cmake_and_ninja: false
          install_ccache: true
          install_conan: false

      - uses: Interstellar-Network/gh-actions/prepare_rust@v3-dev
        with:
          use_toolchain_toml: "true"
          toolchain_components: "rustfmt,clippy"

      ##########################################################################

      - uses: Interstellar-Network/gh-actions/install-sgx-sdk@v3-dev

      # TODO? do we need to "cd enclave/"[we can probably consider enclave/ as internal implementation details?]
      - uses: Interstellar-Network/gh-actions/rust-lint@v3-dev
        with:
          # - clippy: pass --release b/c make always compile in release; so might as well avoid recompiling
          #   from scratch just for the linters.
          # - need to disable unknown-lints b/c the workspace toolchain is old; and clippy does not understand
          #   "#[allow(clippy::derive_partial_eq_without_eq)]" in interstellar-pallets/pallets/ocw-circuits/src/lib.rs
          #   And that is used both in this repo, and integritee-node which is using a more recent toolchain.
          clippy_args: "--release -- -D warnings -A unknown-lints"
      # TODO pass "-A unknown-lints" to clippy
